AWSTemplateFormatVersion: '2010-09-09'

Description: MySQL RDS Database

Parameters:

  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id

  RDSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true
    Description: Master password for the RDS database
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "^[a-zA-Z0-9!#$%^&*()_+=-]+$"
    

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Database Subnet Group
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id

  MyDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:

      Engine: mysql
      EngineVersion: "8.0"

      DBInstanceClass: db.t3.micro

      AllocatedStorage: 20
      StorageType: gp3
      StorageEncrypted: true

      DBName: twotierdb

      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword

      PubliclyAccessible: false
      MultiAZ: false

      BackupRetentionPeriod: 7

      DeletionProtection: false

      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId

      DBSubnetGroupName: !Ref DBSubnetGroup

      Tags:
        - Key: Name
          Value: MySQLDatabase

Outputs:

  DatabaseEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt MyDatabase.Endpoint.Address

  DatabaseIdentifier:
    Description: RDS Instance Identifier
    Value: !Ref MyDatabase

  DBSubnetGroupName:
    Description: Database Subnet Group
    Value: !Ref DBSubnetGroup